# TRANSPOSICIÓN, SUMA DE MATRICES Y ESCALARES

Transponer es cambiar filas por columnas,

![](./imagenes/img10.png)

si por ejemplo se tiene un vector, transponer es cambairlos a un vector columna. Si se tiene una matriz de 3x2, al transponerla se convierte en una matriz de 2x3, es de anotar que la diagonal de la matriz no cambia.

In [1]:
# Librerías a utilizar
import numpy as np

In [10]:
# Elementos a utilizar
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2], [3,4], [5,6]])
tensor = np.array([
    [[1,2,3, 30], [4,5,6, 31], [7,8,9, 32]],
    [[11,12,13, 33], [14,15,16, 34], [17,18,19, 35]],
    [[21,22,23, 36], [24,25,26, 37], [27,28,29, 38]]
])

La transpueta en python es la función .T, sin embargo, es muy buena practica que los elementos transpuestos le agreguemos en el nombre un '_t'

In [3]:
# Transpuesta de un escalar
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

Tiene sentido que un escalar arroje error al realizar la transpuesta, ya que no tiene ni filas ni columnas

In [4]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


Para vectores no se va a notar la tranpuesta, siempre va a arrojar el mismo resultado.

In [6]:
matriz_t = matriz.T
print('matriz: ', matriz)
print('matriz_t: ', matriz_t)

matriz:  [[1 2]
 [3 4]
 [5 6]]
matriz_t:  [[1 3 5]
 [2 4 6]]


Se puede observar como se realizo la transpuesta de la matriz, ahora se halla sus dimensiones

In [7]:
print('matriz shape: ', matriz.shape)
print('matriz_t shape: ', matriz_t.shape)

matriz shape:  (3, 2)
matriz_t shape:  (2, 3)


Se ve como cambia de una dimension 3x2 a una 2x3. 

In [11]:
tensor_t = tensor.T
print('tensor: ', tensor)
print('tensor_t: ', tensor_t)

tensor:  [[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]
tensor_t:  [[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


En el caso del tensor, se paso de tres matrices de 4x3 a cuatro matrices de 3x3.

Una regla de las matrices es que la transpuest de una matriz transpuesta en la misma matriz, es decir:

$$ (A^{t})^{t}=A $$

In [13]:
matriz_t_t = matriz_t.T
print('matriz: ', matriz)
print('matriz_t_t: ', matriz_t_t)

matriz:  [[1 2]
 [3 4]
 [5 6]]
matriz_t_t:  [[1 2]
 [3 4]
 [5 6]]


Se puede observar que efectivamente es la misma matriz, la transpuesta es mucha utilidad cuando se desea resolver problemas matriciales con n incognitas, que junto con otras operaciones nos ayuda a solucionar estos problemas.

En la suma de matrices los elementos que se suma son los que tiene la misma posición en filas y columnas, es decir:

$$
\begin{bmatrix}
 a_{11}&a_{12}\\ 
 a_{21}&a_{22} 
\end{bmatrix}+\begin{bmatrix}
 b_{11}&b_{12}\\ 
 b_{21}&b_{22} 
\end{bmatrix}=\begin{bmatrix}
 a_{11}+b_{11}&a_{12}+b_{12}\\ 
 a_{21}+b_{21}&a_{22}+b_{22} 
\end{bmatrix}
$$

Donde tanto la matriz A como la matriz B deben tener las mismas dimensiones.

In [14]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5], [4,3], [2,1]])
C = A + B
print('A:', A)
print('B:', B)
print('C:', C)

A: [[1 2]
 [3 4]
 [5 6]]
B: [[6 5]
 [4 3]
 [2 1]]
C: [[7 7]
 [7 7]
 [7 7]]


Se observa que efectivamente la suma es como se definio en la ecuación, ahora se prueba la suma entre una matriz y un escalar.

In [15]:
D = matriz + escalar
print('matriz: ', matriz)
print('escalar: ', escalar)
print('matriz + escalar: ', D)

matriz:  [[1 2]
 [3 4]
 [5 6]]
escalar:  5.679
matriz + escalar:  [[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]


El escalar suma a cada uno de los elementos del escalar

$$
\begin{bmatrix}
 a_{11}&a_{12}\\ 
 a_{21}&a_{22} 
\end{bmatrix}+\alpha =\begin{bmatrix}
 a_{11}+\alpha&a_{12}+\alpha\\ 
 a_{21}+\alpha&a_{22}+\alpha 
\end{bmatrix}
$$