# SUMA DE MATRICES Y VECTORES (BROADCASTING)

En python es posible sumar matrices y vectores siempre que se cumpalan con las reglas del broadcasting

In [1]:
# Se importa las librerías necesarias
import numpy as np

In [2]:
# Creación de datos
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2], [3,4], [5,6]])

In [3]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

En este caso no funciona el broadcasting, ya que la matriz es de 3x2, mientras que el vector es de 3 elementos o que seria lo mismo de 1x3, lo cuál los dos elementos tienen diferentes tamaño de columnas.

In [6]:
A = matriz.T + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


En este caso se tiene una matriz de 2x3 que se suma un vector de 3 elementos que es lo mismo de 1x3. Lo que realiza el broadcasting es repetir este vector en cada fila hasta ser una matriz de 2x3 y luego sumarlo a la primera matriz con tamaño 2x3

In [8]:
C = matriz + 42
print(C)

[[43 44]
 [45 46]
 [47 48]]


Se tiene una matriz de 3x2 que se suma un escalar con tamaño 1x1, como se puede crear una matriz desde 1x1 hasta 3x2, broadcasting lo que hace es copiar el escalar hasta crear una matriz de 3x2 para luego sumarlo a la primera matriz de 3x2.

In [9]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


De igual forma si se suma la matriz de 3x2 por otra de 3x1, broadcasting lo que realiza es copiar la columna y crear otra hasta ser una matriz de 3x2 para luego sumarla a la primera matriz de 3x2