# LA MATRIZ DIAGONAL Y LA MATRIZ SIMÉTRICA: SUS PROPIEDADES

In [1]:
import numpy as np

En clases anteriores se mostraron matrices especiales como por ejemplo la matriz identidad, la cual es:

$$
\begin{bmatrix}
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{bmatrix}
$$

Ademas, existen operaciones especiales como por ejemplo el producto interno de una matriz A por su inversa el cuál da como resultado la matriz identidad:

$$
A\cdot A^{-1}=Id
$$

Por otro lado, tambien se tiene la matriz singular, la cuál no tiene inversa:

$$
S\rightarrow \notin S^{-1}
$$

Es hora de ver otros tipos de matrices

In [4]:
# Se crea el vector
vector = np.array([1,2,3,4,5])
# Se crea la matriz con la diagonal con los elementos del vector
matriz = np.diag(vector)

print('matriz diagonal:\n', matriz)

matriz diagonal:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


A este tipo de matrices se le conoce como diagonales, los cuales sus elementos son igual a cero menos en la diagonal de la matriz, es de anotar que las matrices diagonales no necesariamente deben ser cuadradas, como por ejemplo

In [5]:
print('matriz diagonal:\n', matriz[0:4,0:3])
print('matriz diagonal:\n', matriz[0:3,0:4])

matriz diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]
matriz diagonal:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


Una propiedad importante de las matrices diagonales, es que cuando se multiplican por un vector, no estan haciendo una combinación lineal de las distintas coordenadas, para demostrar esto se tiene el siguiente producto interno de dos matrices

$$
\begin{bmatrix}
1 & 0 & 0 & 0\\ 
0 & 2 & 0 & 0\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 4
\end{bmatrix}
\cdot \begin{bmatrix}
x_{1} \\ 
x_{2} \\ 
x_{3} \\ 
x_{4}
\end{bmatrix}
$$

Si se realiza el calculo, por ejemplo con x1, este solo se multiplica con un solo elemento, el resto multiplica por cero por lo que no se aplica una combinación lineal, en python puede mostrarse como:

In [6]:
# Se crea la matriz diagonal
A = np.diag([2,3,4,5])
print('A:\n', A)
# Se crea el vector
v1 = np.array([[1,1,1,1]])
print('v1:\n', v1)
# El resultado del producto interno de estos dos es
print('A.v1^T:\n', A.dot(v1.T))

A:
 [[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
v1:
 [[1 1 1 1]]
A.v1^T:
 [[2]
 [3]
 [4]
 [5]]


No devuelve un vector que no es ninguna combinación lineal, simplemente estan amplificados los valores del vector. La matriz inversa resulta ser 1 divido por cada uno de los elementos de la matriz, lo cual se muestra en python

In [7]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print('A^-1:\n', A_inv)

A^-1:
 [[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


Para comprobar que efectivamente esta es la matriz inversa se recurre a la propiedad

$$
A\cdot A^{-1}=Id
$$

In [8]:
identidad = A.dot(A_inv)
print('Id:\n', identidad)

Id:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Se obtiene la matriz identidad.

In [9]:
A_inv_calc = np.linalg.inv(A)
print('A^-1:\n', A_inv_calc)

A^-1:
 [[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


Con la función linalg.inv da el mismo resultado que la matriz inversa anterior.

Por otro lado, una matriz es simetrica cuando su transpuesta es la misma matriz, es decir

$$
A=A^{T}
$$

Es de recordar que la transpuesta es cambiar las filas por las columnas, por tanto toda matriz diagonal es simetrica, se muestran algunos casos de matrices simetricas.

In [10]:
print('A:\n', A)
print('A^T:\n', A.T)

A:
 [[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
A^T:
 [[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


Se demuestra que la matriz A es simetrica por ser una matriz diagonal, Ahora se define otra matriz mas complicada.

In [11]:
simetrica = np.array([[1,2,3],
                      [2,-1,7],
                      [3,7,11]])
print('simetrica:\n', simetrica)
print('simetrica.T:\n', simetrica.T)

simetrica:
 [[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
simetrica.T:
 [[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


Se tiene la misma matriz, por tanto la matriz es simétrica.

se tiene la siguiente propiedad:

$$
(A\cdot B)^{T}=B^{T}\cdot A^{T}
$$

El cual solamente para matrices simétricas se cumple que:
$$
(A\cdot B)^{T}=B\cdot A\newline solo\ para\ matrices\ simetricas
$$