# MATRICES ORTOGONALES Y SUS PROPIEDADES

In [1]:
import numpy as np

Una matriz es ortogonal cuando todas sus filas son mutuamente ortonormales y todas sus columnas son mutuamente ortonormales.

In [2]:
# Se crea la matriz
matriz = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

print('matriz:\n', matriz)

matriz:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


A proposito se crea la matriz identidad que se sabe es ortogonal, sin embargo se comprueba que sea ortogonal en python

In [3]:
print('ortogonal:\n', matriz[:,0].dot(matriz[:,1]))

ortogonal:
 0


De esta forma con el producto interno igual a 0, se compruba que los primeros vectores son ortogonales, para entender mejor, se tiene una matriz con tres vectores

$$
\begin{bmatrix}
v_{1} & v_{2} & v_{3}
\end{bmatrix}
$$

de tal forma que los tres vectores son ortogonale uno del otro

$$
v_{1} \perp v_{2}\newline
v_{1} \perp v_{3}\newline
v_{2} \perp v_{3}
$$


In [4]:
print('ortogonal v1 v2:\n', matriz[:,0].dot(matriz[:,1]))
print('ortogonal v1 v3:\n', matriz[:,0].dot(matriz[:,2]))
print('ortogonal v2 v3:\n', matriz[:,1].dot(matriz[:,2]))

ortogonal v1 v2:
 0
ortogonal v1 v3:
 0
ortogonal v2 v3:
 0


De esta forma se comprueba que todos los vectores son ortogonales entre si mismo, por lo que la matriz es ortogonal, ahora se revisa si son ortonomales

In [5]:
print('ortonormal v1:\n', np.linalg.norm(matriz[:,0]))
print('ortonormal v2:\n', np.linalg.norm(matriz[:,1]))
print('ortonormal v3:\n', np.linalg.norm(matriz[:,2]))

ortonormal v1:
 1.0
ortonormal v2:
 1.0
ortonormal v3:
 1.0


Todos los vectores tienen norma 1 por lo tanto todos los vectores son ortonormales, pero en este caso solo se evaluaron las columnas y para que una matriz sea ortogonal tambien se necesita que sus filas sean ortonormales, pero primero se observa si son ortogonales.

In [6]:
print('ortogonal f1 f2:\n', matriz[0,:].dot(matriz[1,:]))
print('ortogonal f1 f3:\n', matriz[0,:].dot(matriz[2,:]))
print('ortogonal f2 f3:\n', matriz[1,:].dot(matriz[2,:]))

ortogonal f1 f2:
 0
ortogonal f1 f3:
 0
ortogonal f2 f3:
 0


EL resultado del producto interno entre filas de como resultado 0, por lo que entre filas son ortogonales. Ahora se evalua la norma entre las normas.

In [7]:
print('ortonormal f1:\n', np.linalg.norm(matriz[0,:]))
print('ortonormal f2:\n', np.linalg.norm(matriz[1,:]))
print('ortonormal f3:\n', np.linalg.norm(matriz[2,:]))

ortonormal f1:
 1.0
ortonormal f2:
 1.0
ortonormal f3:
 1.0


Entre filas se obtiene de norma 1 por lo que las filas son ortonormales, por lo tanto la matriz es ortogonal. En matrices no existe el concepto de matriz ortonormal, ya que al trabajar con vectores ortonormales no da espacio para la matriz ortonormal, se dice que es una matriz ortogonal que se compone de vectores ortonormales. Solo para matrices ortogonales se cumple la siguiente propiedad:

$$
A^{T}\cdot A=A\cdot A^{T}=Id\newline Solo\ para\ matrices\ ortogonales
$$

por tanto 

$$
A^{T}=A^{-1}
$$

Ahora se muesta como generar matrices ortogonales en python, la cuál se apoya en las funciones trigonometricas seno y coseno.



In [8]:
# Se genera la matriz con una rotación sobre el eje para generar una 
# matriz que sea orotogonal
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100), np.cos(100)]])
print('A:\n', A)

A:
 [[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


Ahora se comprueba que esta matriz es ortogonal

In [9]:
print('Ortonormal f1', np.linalg.norm(A[0,:]))
print('Ortonormal f2', np.linalg.norm(A[1,:]))
print('Ortonormal c1', np.linalg.norm(A[:,0]))
print('Ortonormal c2', np.linalg.norm(A[:,1]))

Ortonormal f1 0.9999999999999999
Ortonormal f2 0.9999999999999999
Ortonormal c1 0.9999999999999999
Ortonormal c2 0.9999999999999999


Se observa que los valores son muy cercanos a 1, debido a que computacionalmente queda decimales perdidos, por lo que hay que tener especial cuidado al realizar estos calculo, ya que para este ejemplo la solución verdadera es 1 para cada norma.

Ahora, se halla el producto interno entre filas y columnas.

In [10]:
print('Ortogonal f1 f2',A[0,:].dot(A[1,:]))
print('Ortogonal c1 c2',A[:,0].dot(A[:,1]))

Ortogonal f1 f2 0.0
Ortogonal c1 c2 0.0


El producto interno de filas y columnas es 0, por lo que son ortogonales, esto demuestra que no necesariamente la identidad es la unica matriz que es ortogonal. Ahora se comprueba la propiedad

$$
A^{T}\cdot A= A\cdot A^{T}=Id
$$

In [11]:
A_t = A.T
print('A^T.A:\n', A_t.dot(A))
print('A.A^T', A.dot(A_t))

A^T.A:
 [[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
A.A^T [[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


Aunque no parezca a simple vista, se tiene la matriz identidad, ya que la diagonal es 1 y los elementos de la diagonal son ceros, pero debido al error computacional aparece números elevados a una potencia muy negativa, por lo que son muchos decimales en cero, es decir, números muy pequeños que se tomar como cero. Nuevamente se debe tener cuidado con el error computacional, porque puede generar conclusiones que no son ciertas.

In [12]:
A_inv = np.linalg.inv(A)
print('A^-1:\n',A_inv)
print('A^T:\n', A_t)

A^-1:
 [[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]
A^T:
 [[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


Se puede ver que tanto la inversa como la transpuesta de A es la misma matriz.

In [13]:
print('1/A^T.A:\n', 1/A_t.dot(A))

1/A^T.A:
 [[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]


Al dividirlo se obtiene una matriz con unos valores muy grandes, por lo que hay que tener cuidado con las operaciones, ya que se puede estar amplificando el error, para este caso debio haber aparecido una operación no definida ya que se estaba dividiendo por cero.