# TIPOS ESPECIALES DE MATRICES: IDENTIDAD, INVERSA, SINGULARES

In [1]:
# Se importa la librerías necesarias
import numpy as np

In [2]:
# El método np.eye crea una matriz identidad, se le ingresa como 
# parametro el tamaño de la matriz cuadrada
identidad = np.eye(4)
print('Identidad:\n', identidad)

Identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


La matriz identidad, es una matriz cuadrada en la cual en su diagonal esta conformada por 1 y el resto por 0. Es de anotar que todos los números son de tipo float, el cuál se puede ver por el punto que se coloca al lado del número.

In [3]:
# Se define un vector con 4 elementos
vector = np.array([[2], [3], [5], [7]])
print('vector:\n', vector)
print('identidad.vector:\n', identidad.dot(vector))

vector:
 [[2]
 [3]
 [5]
 [7]]
identidad.vector:
 [[2.]
 [3.]
 [5.]
 [7.]]


Al realizar el producto interno entre la identidad y el vector, da como resultado el mismo vector, por tanto la matriz identidad es el elemento neutro de las matrices, es como por ejemplo el número 1 para los escalares.

Una operación bastante conocida es la de transformación lineal, que es aplicar a un vector el producto interno con una matriz, con el fin de obtener un nuevo vector, en pocas palabras es multiplicar. Por ejemplo, se tiene un vector (1, 1), el cuál se puede transformar como:

$$
\begin{bmatrix}
2 & 3\\ 
4 & 5
\end{bmatrix}\cdot \begin{bmatrix}
1\\1 
\end{bmatrix}=\begin{bmatrix}
2+3\\ 4+5
\end{bmatrix}
$$

Otra matriz que es muy útil es la inversa A^-1, la cuál al multiplicarla por A da la matriz identidad

$$
A\cdot A^{-1}=Identidad
$$


In [4]:
# Se crea una matriz a la cual se quiere calcular al inversa
A = np.array([[1,0,1], [0,1,1], [-1,1,1]])
print('A:\n', A)
# La inversa se calcula con la función de numpy linalg.inv
inversa_A = np.linalg.inv(A)
print('A^-1:\n', inversa_A)

A:
 [[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]
A^-1:
 [[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


La matriz inversa de A es otra matriz con las mismas dimensiones que la matriz A, ahora se prueba si el producto interno de estos dos da la matriz identidad.

In [5]:
print('A.A^-1:\n', A.dot(inversa_A))

A.A^-1:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Efectivamente al realizar el producto interno de A con su inversa, el resultado es la matriz identidad. 

Sin embargo, no todas la matrices tienen la inversa, a este tipo de matrices se les conoce como matrices singulares, por ejemplo la siguiente matriz:

In [7]:
singular = np.array([[1,1], [1,1]])
print('singular:\n', singular)

singular:
 [[1 1]
 [1 1]]


In [8]:
# Hallando su inversa
print(np.linalg.inv(singular))

LinAlgError: Singular matrix

Devuelve el error, en este caso arroja un error de 'Singular matrix'. Además, las matrices inversas solo pueden calcularse en matrices cuadradas. El tener matrices inversas permite realizar operaciones como por ejemplo para el caso de ecuaciones lineales, ya que:

$$
A\cdot x=b\newline
x=b\cdot A^{-1} 
$$

Por tanto la inversa ayuda para encontrar el resultado de un sistema de ecuaciones lineales