# APLICACIÓN DE LA INVERSA DE UNA MATRIZ PARA RESOLVER UN SISTEMA DE ECUACIONES LINEALES

In [2]:
# Se importa las librerías necesarias
import numpy as np
# Se agrega esta línea para colocar como 0 todos aquellos valores que
# son muy cercanos a 0
np.set_printoptions(suppress=True)

En una clase anterior se tenía un sistema de ecuaciones lineales como:

$$
3x+y=1\newline
2x+y=1
$$

El cual en forma matricial se representa como:

$$
A\cdot x=b
$$
$$
\begin{bmatrix}
3 & 1\\ 2 & 1
\end{bmatrix}
\begin{bmatrix}
x \\ y 
\end{bmatrix}=
\begin{bmatrix}
1\\1 
\end{bmatrix}
$$

In [6]:
# Se crea la matriz
A = np.array([[3,1], [2,1]])
print('A:\n', A)
b = np.array([[1], [1]])
print('b:\n', b)

A:
 [[3 1]
 [2 1]]
b:
 [[1]
 [1]]


Se halla la inversa de A con la función linalg.inv

In [7]:
inversa_A = np.linalg.inv(A)
print('inversa_A:\n', inversa_A)

inversa_A:
 [[ 1. -1.]
 [-2.  3.]]


Se halla x sabiendo que:

$$
A\cdot x=b\newline
x=A^{-1}\cdot b
$$

In [9]:
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


Da como resulta para la matriz x de (0, 1), ahora se prueba en la sistema matricial a mano:

$$
3x+y=1\newline
3*0+1*1=1
$$
$$
2x+y=1\newline
2*0+1*1=1
$$

Ahora, se este cálculo realizado a mano se puede escribir en código como:

In [10]:
print(A.dot(x))

[[1.]
 [1.]]


Se muestra el mismo resultado.

Esto significa, que para este caso, la primera columna de la matriz A, no es representativa para la matriz b que son los resultados. Si se mantiene la matriz A, es decir, se mantiene los coeficientes del sistema de ecuaciones, siempre la misma matriz inversa de A funciona para calcular los valores de la matriz x, los cuales varían segun la matriz b. Por ejemplo.

$$
3x+y=3\newline
2x+y=7
$$

Se utiliza la misma matriz inversa

In [11]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))
print('sol_2:\n', sol_2)

sol_2:
 [[-4.]
 [15.]]


Se prueba para saber si este es solución

In [12]:
print(A.dot(sol_2))

[[3.]
 [7.]]


Efectivamente se halla una nueva matriz x, por tanto el sistema de soluciones x depende del resultado b, y la inversa de A siempre va a ser unica para la matriz A.

Sin embargo, esta forma de resolver un sistema de ecuaciones lineales no es eficiente de manera computacional y debemos recurrir a otro métodos para su solución.

