# PRODUCTO INTERNO ENTRE UNA MATRIZ Y UN VECTOR

In [1]:
# Se importa la librerías necesarias
import numpy as np


In [2]:
# Creación de datos
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4], [5,6]])

In [5]:
# Se multiplica la matriz con el vector
A = matriz * vector
# Producto interno
B = matriz.dot(vector)
print('Matriz:\n', matriz)
print('Vector:\n', vector)
print('Multiplicacion:\n', A)
print('Producto interno:\n', B)

Matriz:
 [[1 2]
 [3 4]
 [5 6]]
Vector:
 [2 3]
Multiplicacion:
 [[ 2  6]
 [ 6 12]
 [10 18]]
Producto interno:
 [ 8 18 28]


La multiplicación de una matriz 3*2 por un vector de 2, da como resultado una matriz de 3x2, ya que se hace un braodcasting hasta obtener el tamaño de la matriz, es decir

$$
\begin{bmatrix}
1 & 2\\ 
3 & 4\\ 
5 & 6
\end{bmatrix}\begin{bmatrix}
2 & 3
\end{bmatrix} = \begin{bmatrix}
1*2 & 2*3\\ 
3*2 & 4*3\\ 
5*2 & 6*3
\end{bmatrix}=\begin{bmatrix}
2 & 6\\ 
6 & 12\\ 
10 & 18
\end{bmatrix}
$$

El producto interno se realiza la operación como:

$$
\begin{bmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}\\ 
a_{31} & a_{32}
\end{bmatrix}\cdot \begin{bmatrix}
b_{1}\\b_{2} \end{bmatrix}
=\begin{bmatrix}
a_{11}*b_{1}+a_{12}*b_{2}\\
a_{21}*b_{1}+a_{22}*b_{2}\\ 
a_{31}*b_{1}+a_{32}*b_{1}\end{bmatrix}
$$

Para este caso, 

$$
\begin{bmatrix}
1 & 2\\3 & 4\\ 5 & 6
\end{bmatrix}\cdot \begin{bmatrix}
2\\3 \end{bmatrix}
=\begin{bmatrix}
1*2+2*3\\3*2+4*3\\ 
5*2+6*3\end{bmatrix} = \begin{bmatrix}
8\\ 18 \\ 28 \end{bmatrix}
$$


El producto interno se puede expresar de dos formas en python como:

In [6]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]
