# PROPIEDADES DE LA MASTRICES: LA MULTIPLICACIÓN DE MATRICES ES ASOCIATIVA Y DISTRIBUTIVA, NO ES CONMUTATIVA

In [1]:
# Se importa las librerías necesarias
import numpy as np

In [2]:
# Matrices necesarias para el desarrollo de la clase
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])
C = np.array([[3,1], [4,2]])

## Asociativa

Es asociativa si:

$$
A \cdot (B \cdot C) = (A \cdot B) \cdot C
$$

In [5]:
ABC = A.dot(B.dot(C))
AB_C = A.dot(B).dot(C)
print('A.(B.C):\n', ABC)
print('(A.B).C:\n', AB_C)

A.(B.C):
 [[ 60  26]
 [145  63]
 [295 129]]
(A.B).C:
 [[ 60  26]
 [145  63]
 [295 129]]


Aunque esta no es la manera formal de probar una propiedad, si nos demuestra que el producto interno matrices cumple con la propiedad asociativa. **Es asociativa.** 

## Distributiva
Es distributiva si:

$$
A\cdot(B+C)=(A\cdot B)+(A\cdot C)
$$

In [7]:
D = A.dot(B + C)
E = (A.dot(B)) + (A.dot(C))
print('A.(B+C):\n', D)
print('(A.B)+(A.C):\n', E)
print(D==E)

A.(B+C):
 [[ 26  17]
 [ 62  41]
 [122  83]]
(A.B)+(A.C):
 [[ 26  17]
 [ 62  41]
 [122  83]]
[[ True  True]
 [ True  True]
 [ True  True]]


Por tanto la operación producto punto **es distributiva**

## Conmutativa

Es conmutativa si:

$$
B\cdot C = C\cdot B
$$

In [8]:
F = B.dot(C)
G = C.dot(C)
print('A.B:\n', F)
print('B.A:\n', G)
print(F == G)

A.B:
 [[15  7]
 [10  4]]
B.A:
 [[13  5]
 [20  8]]
[[False False]
 [False False]]


Por tanto se puede decir que la operación producto interno **NO es asociativa**

Ahora se prueba con la operación producto interno de vectores

In [9]:
# Se crean los vectores
v1 = np.array([[2],[7]])
v2 = np.array([[3], [5]])

In [10]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)
print('v1.v2:\n', v1_tv2)
print('v2.v1:\n', v2_tv1)

v1.v2:
 [[41]]
v2.v1:
 [[41]]


Se observa que para el producto interno **Es conmutativa solo en vectores, en matrices no aplica**