# TRANSPOSICIÓN DE UN PRODUCTO DE MATRICES

In [1]:
# Se importa la librerías necesarias
import numpy as np

In [5]:
# Matrices para el desarrollo de la clase
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])

In [6]:
print('A:\n', A)
print('B:\n', B)

A:
 [[ 2  3]
 [ 5  7]
 [11 13]]
B:
 [[1 3]
 [2 1]]


En matemáticas existe una propiedad para las matrices que es:

$$
(A\cdot B)^{t}=B^{t}\cdot A^{t}
$$
ademas, 
$$
((A\cdot B)^{t})^{t} = A\cdot B
$$

Lo cuál permite trabajar con dos matrices, para hallar una posible solución a un sistema lineal de ecuaciones.

In [8]:
AB_t = A.dot(B).T
B_tA_t = B.T.dot(A.T)
print('(A.B)^t:\n', AB_t)
print('B^t.A^t:\n', B_tA_t)
print(AB_t == B_tA_t)

(A.B)^t:
 [[ 8 19 37]
 [ 9 22 46]]
B^t.A^t:
 [[ 8 19 37]
 [ 9 22 46]]
[[ True  True  True]
 [ True  True  True]]


Se demuestra que se cumple con la propiedad antes dicha.